org: hunterlong
app: pantry
service: pantry
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    JWT_SECRET_KEY: ${param:JWT_SECRET_KEY}
    OPENAI_API_KEY: ${param:OPENAI_API_KEY}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - ${param:TODO_TABLE_ARN}
        - ${param:FOOD_TABLE_ARN}
        - ${param:USER_TABLE_ARN}
        - ${param:USER_TABLE_ARN}/index/*

functions:
  jwtAuthorizer:
    handler: src/functions/auth/jwtAuthorizer.default
  register:
    handler: src/functions/auth/register.default
    events:
      - http:
          path: /register
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
  login:
    handler: src/functions/auth/login.default
    events:
      - http:
          path: /login
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
  deleteTodo:
    handler: src/functions/todos/deleteTodo.default
    events:
      - http:
          path: /todos/{id}
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
          authorizer:
            name: jwtAuthorizer
  addTodo:
    handler: src/functions/todos/addTodo.default
    events:
      - http:
          path: /todos
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
          authorizer:
            name: jwtAuthorizer
  getTodos:
    handler: src/functions/todos/getTodos.default
    events:
      - http:
          path: /todos
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
          authorizer:
            name: jwtAuthorizer
  getTodoById:
    handler: src/functions/todos/getTodoById.default
    events:
      - http:
          path: /todos/{id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
          authorizer:
            name: jwtAuthorizer
  updateTodo:
    handler: src/functions/todos/updateTodo.default
    events:
      - http:
          path: /todos/{id}
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
          authorizer:
            name: jwtAuthorizer
  createFoodItem:
    handler: src/functions/openai/createFoodItem.default
    timeout: 30
    events:
      - http:
          path: /food
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
          authorizer:
            name: jwtAuthorizer

resources: 
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    FoodTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FoodTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

# # Reference on GlobalSecondaryIndexes:
# # https://stackoverflow.com/questions/57322645/how-to-define-dynamodb-table-with-global-secondary-index-in-serverless-framework

# # Reference for secondary index IAM permissions
# # https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/iam-policy-specific-table-indexes.html